// AI-generated. See PROMPT.md for the prompts and model used.

import { fireEvent, render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";
import { LearningsPanel } from "../components/transcript/LearningsPanel";
import type { SessionLearning } from "../lib/types";

const learning = (over: Partial<SessionLearning> = {}): SessionLearning => ({
  id: "l1",
  title: "Marked done without running tests",
  episode_event_uuids: ["u-3", "u-6"],
  what_went_wrong: "Reported the work finished before running any tests.",
  what_would_have_prevented: "Run the suite before reporting done.",
  root_cause: "missing_verification",
  attributed_to: "agent",
  confidence: 0.95,
  severity: "high",
  model: "agent",
  generated_at: "2026-05-01T10:00:00.000Z",
  summarized_event_count: 47,
  ...over,
});

describe("LearningsPanel", () => {
  it("shows the empty state when there are no learnings", () => {
    render(<LearningsPanel learnings={[]} onJumpToEvent={() => {}} />);
    expect(screen.getByTestId("learnings-empty")).toBeTruthy();
  });

  it("renders a card with humanized root-cause chip and provenance", () => {
    render(<LearningsPanel learnings={[learning()]} onJumpToEvent={() => {}} />);
    expect(screen.getByTestId("learning-card")).toBeTruthy();
    expect(screen.getByText("Marked done without running tests")).toBeTruthy();
    expect(screen.getByText("missing verification")).toBeTruthy();
    expect(screen.getByText(/generated by agent at event 47/)).toBeTruthy();
  });

  it("calls onJumpToEvent with the evidence uuid", () => {
    const onJump = vi.fn();
    render(<LearningsPanel learnings={[learning()]} onJumpToEvent={onJump} />);
    const links = screen.getAllByTestId("learning-evidence");
    expect(links).toHaveLength(2);
    fireEvent.click(links[0] as HTMLElement);
    expect(onJump).toHaveBeenCalledWith("u-3");
  });

  it("toggles raw JSON view", () => {
    render(<LearningsPanel learnings={[learning()]} onJumpToEvent={() => {}} />);
    fireEvent.click(screen.getByTestId("learnings-raw-toggle"));
    expect(screen.getByText(/"root_cause": "missing_verification"/)).toBeTruthy();
  });
});
