// AI-generated. See PROMPT.md for the prompts and model used.

import { useState } from "react";
import { cn } from "../../lib/cn";
import type { SessionLearning } from "../../lib/types";
import { MarkdownView } from "./MarkdownView";

const ROOT_CAUSE_LABEL: Record<string, string> = {
  underspecified_request: "underspecified request",
  instruction_not_followed: "instruction not followed",
  missing_verification: "missing verification",
  task_derailment: "task derailment",
  context_loss: "context loss",
  environment_or_tooling: "environment or tooling",
};

const severityClass = (severity: string | null): string => {
  if (severity === "high") return "learning-severity learning-severity-high";
  if (severity === "medium") return "learning-severity learning-severity-medium";
  return "learning-severity learning-severity-low";
};

const tally = (learnings: SessionLearning[]): string => {
  const counts: Record<string, number> = {};
  for (const l of learnings)
    counts[l.severity ?? "unspecified"] = (counts[l.severity ?? "unspecified"] ?? 0) + 1;
  const parts = ["high", "medium", "low", "unspecified"]
    .filter((s) => counts[s])
    .map((s) => `${counts[s]} ${s}`);
  return parts.length > 0 ? ` (${parts.join(", ")})` : "";
};

const provenance = (l: SessionLearning): string => {
  const who =
    l.model === "agent" ? "agent" : l.model === "heuristic" ? "heuristic" : (l.model ?? "unknown");
  const at = l.summarized_event_count != null ? ` at event ${l.summarized_event_count}` : "";
  return `generated by ${who}${at}`;
};

export const LearningsPanel = ({
  learnings,
  onJumpToEvent,
}: {
  learnings: SessionLearning[];
  onJumpToEvent: (eventUuid: string) => void;
}) => {
  const [raw, setRaw] = useState(false);

  if (learnings.length === 0) {
    return (
      <div className="p-8 text-center text-sm text-muted-foreground" data-testid="learnings-empty">
        No issues detected this session.
      </div>
    );
  }

  return (
    <div className="px-4 py-4" data-testid="learnings-panel">
      <div className="flex items-center justify-between mb-3">
        <div className="text-xs text-muted-foreground">
          {learnings.length} {learnings.length === 1 ? "issue" : "issues"}
          {tally(learnings)}
        </div>
        <button
          type="button"
          onClick={() => setRaw((v) => !v)}
          className="text-xs px-2 py-1 rounded border border-border hover:bg-muted"
          data-testid="learnings-raw-toggle"
        >
          {raw ? "View rendered" : "View raw"}
        </button>
      </div>

      {raw ? (
        <pre className="text-xs overflow-auto p-3 rounded border border-border bg-muted">
          {JSON.stringify(learnings, null, 2)}
        </pre>
      ) : (
        <div className="space-y-4">
          {learnings.map((l, i) => (
            <div
              key={l.id}
              className="p-3 rounded border border-border"
              data-testid="learning-card"
            >
              <div className="flex items-baseline gap-2">
                <span className="text-xs text-muted-foreground tabular-nums">{i + 1}.</span>
                <h3 className="text-sm font-semibold flex-1">{l.title}</h3>
              </div>
              <div className="flex items-center flex-wrap gap-2 mt-1.5 mb-2">
                <span className="tag-chip pointer-events-none">
                  {ROOT_CAUSE_LABEL[l.root_cause] ?? l.root_cause}
                </span>
                <span className="tag-chip pointer-events-none">{l.attributed_to}</span>
                {l.severity && <span className={severityClass(l.severity)}>{l.severity}</span>}
                <span className="text-xs text-muted-foreground tabular-nums">
                  confidence {l.confidence.toFixed(2)}
                </span>
              </div>

              <div className="text-xs font-semibold text-muted-foreground mt-2">
                What went wrong
              </div>
              <MarkdownView>{l.what_went_wrong}</MarkdownView>

              <div className="text-xs font-semibold text-muted-foreground mt-2">
                What would have prevented it
              </div>
              <MarkdownView>{l.what_would_have_prevented}</MarkdownView>

              {l.episode_event_uuids.length > 0 && (
                <div className="mt-2 flex items-center flex-wrap gap-2 text-xs">
                  <span className="text-muted-foreground">Evidence:</span>
                  {l.episode_event_uuids.map((uuid, j) => (
                    <button
                      key={uuid}
                      type="button"
                      onClick={() => onJumpToEvent(uuid)}
                      className={cn("pr-badge cursor-pointer hover:bg-accent")}
                      data-testid="learning-evidence"
                    >
                      event {j + 1} →
                    </button>
                  ))}
                </div>
              )}

              <div className="mt-2 text-[0.6875rem] text-muted-foreground">{provenance(l)}</div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
};
